name: Docs build
on:
-   push

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        permissions: write-all
        steps:
        -   name: Check out main
            uses: actions/checkout@main
        -   name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.10.5
        -   name: Install Poetry
            uses: snok/install-poetry@v1
            with:
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true
        -   name: Install dependencies
            run: poetry install --no-interaction --no-root
        -   name: Install library
            run: poetry install --no-interaction
        -   name: Install pandoc
            run: apt-get -y install pandoc
        -   name: Build documentation
            run: poetry run make html --directory docs/
        -   name: Commit files
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                touch docs/_build/html/.nojekyll
                git add -f docs/_build/
                git commit -m "Update autodoc" -a
    # using https://github.com/marketplace/actions/push-git-subdirectory-as-branch
        -   name: Deploy
            uses: s0/git-publish-subdir-action@develop
            env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: docs/_build/html
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
